import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree, Libre_Caslon_Text, Libre_Caslon_Display } from "next/font/google";

import NavBar from "@/components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-figtree',
});

const libreCaslon = Libre_Caslon_Text({
  subsets: ['latin'],
  weight: ['400', "700"],
  display: 'swap',
  variable: '--font-libre-caslon',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${libreCaslon.variable} antialiased overflow-auto`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
